### ISSUE TITLE
[FRS] Make Space for Makerspace!

### ISSUE THREAD

**Issue by sl194** [OpenSUTD/DiscoverSUTD-2020#23]
**Session Name**
Make Space for Makerspace!

**Abstract**
Create a personalised light stand to display on your desk in the comfort of your humble abode at hostel! Get a taste of working with acrylic, wood and LEDs which you will be working very much with during your years at SUTD!

**Student Organisation organising this Session**
SUTD Makerspace

**Session Intent (What to Expect)**
- Participants will be getting to work with acrylic, wood, sharps, and some electronics to assemble their own light stand.
- Participants do not need any prerequisite knowledge, and just need to be careful during this activity as they will be manually "laser-cutting" their acrylic pieces using a sharp object.
- Participants will be learning how to assemble products from its raw materials and will be given the opportunity to harness their creativity to let their designs shine (both literally and metaphorically)!

**Session Details**
Timing: Wednesday 23 September 2020 7-9pm
Venue: Microsoft Teams (Link: https://tinyurl.com/makerspaceintrosession)
Sign up at: https://tinyurl.com/makespaceformakerspace
Collect introductory kit on either:
- Monday 21 September 2020, 1.30-3.30pm
- Tuesday 22 September 2020, 9-11am

In preparation for the session, 2 EXCO members would need approval to physically access Fab Lab Level 2 Laser Cutters on two days, each lasting for 2 hours, to laser cut materials using self-sourced wood and acrylic. Fab Lab General Manager specified that he requires prior approval from OSA before allowing the Makerspace EXCO members to book the Fab Lab.

For pre-event, on 23 September 2020 at 1300-1900hrs, distribution of the activity kits will be conducted at school. Collection will be spaced out accordingly so that there will not be more than 5 people at one time at one place.

After introduction to the club and some demonstration and briefing through the online meeting, the participants will proceed to do the activity at their own selected locations.

**Speakers/Workshop Facilitators**
Current Makerspace EXCO (Sharmayne Lim, Phoebe Leam, Peter Santosh David, Gan Jia Jie)

**Logistical Details**
Club email address: makerspace@club.sutd.edu.sg

**Comment by jamestiotio** [comment]
Hi @sl194! Looks like an enlightening session heh. Timing looks fine for now. Three points of concern from me:

1. Any ideas on how you are going to distribute the materials for the workshop to the participants if it is conducted virtually on an online video conferencing platform?

2. Since your team is conducting this event virtually, would you like to add your video conference link/URL here? We can add it into the [events page](https://discover.opensutd.org/events.html) for the incoming Freshmores to refer to.

3. Budget is only given if there is really a need for it, so I would advise your team to safely source (most, if not all, of) your budget and logistics first. If our DiscoverSUTD team manages to have some extra budget from our side, we can allocate for Fifth Rows who really need it for their introductory sessions (since introductory sessions are considered to be under discovery week). If you need budget, we would need to raise it to Jia Xin, our supervisor from SUTD's Office of Student Administration. Send us an email [here](mailto:discover@sutd.edu.sg) with your intended budget amount and we will link you up to an email thread with Jia Xin for further discussion.

**Comment by jamestiotio** [comment]
Hi @sl194, also a gentle reminder to obtain approval from OSL for this event. Once you have confirmed the approval, we can proceed with the rest of the process.

**Comment by sl194** [comment]
can can okies @jamestiotio will be sending osl epf/ra by today/tmr

1. we will be distributing materials (activity kits with all the materials required) beforehand at perhaps the canteen/some collection point
2. will provide the link to u soon once event has been approved
3. can okies thanks

**Comment by sl194** [comment]
hi discover sutd team just a note that we have updated the original issue with the details of our microsoft teams link as well sign up link and kit collection dates and timings:

here are the details for easy reference:
Venue: Microsoft Teams (Link: https://tinyurl.com/makerspaceintrosession)
Sign up at: https://tinyurl.com/makespaceformakerspace
Collect introductory kit on either:
- Monday 21 September 2020, 1.30-3.30pm
- Tuesday 22 September 2020, 9-11am

**Comment by jamestiotio** [comment]
Hi @sl194, just want to notify that your sign-up form states that it "is currently not accepting responses". You might want to fix that. Cheers!

**Comment by sl194** [comment]
@jamestiotio it is because we have exceeded the sign up limit of 30 already, that's why we have closed the sign up form cos we don't have enough material to prepare more than that.
