### ISSUE TITLE
[FRS] Light Up Your Life with SUTDio!

### ISSUE THREAD

**Issue by sl194** [OpenSUTD/DiscoverSUTD-2020#25]
**Session Name**
Light Up Your Life with SUTDio!

**Abstract**
Handmade animal lanterns; Easy and Fun to make! 
For all to bring back a mini night light for their hostel desks! 

**Student Organisation organising this Session**
SUTDio

**Session Intent (What to Expect)**
Animal Lanterns will be aimed for freshmores to have a taste of SUTDio craft sessions by offering them an easy and fun activity where they can go back with self-designed paper lanterns that also act as animal patterned night lights. At the same time, it is also a chance for SUTDio to welcome the freshmores with a small tool pack that will come handy during their time in SUTD.

**Session Details**
Number of participants: 20
Venue: Zoom/Microsoft Teams (Link to be shared at a later date)
Date & Time: 17 September 2020 (Thursday), 8-9pm

For pre-event, the EXCO will prepare materials and door gift for lantern making and pack them into individual packets. The Freshmores can then go to ASD SUTDio or OLab physically to collect the materials needed for the session any time until the start of the event.

Collection Plan: _“We plan to use either ASD SUTDio or OLab as our collection point. We will set up a table outside of the collection venue while one of our committee members will sit inside the collection venue. Students will come by, scan the QR code or link to check for their names and just collect the kit. If we are using OLab, OLab is located at building 2 level 4, which is not frequently accessed by any student and thus have little to no human traffic. We will also put a sign further from the collection venue to tell any students approaching the collection venue to collect their kit to wait until there’s nobody there to prevent clustering.”_

For post-event, at 2100hrs – 2130hrs, they will be cleaning up the collection point area and conduct an optional Q&A via Zoom.

**Speakers/Workshop Facilitators**
Current SUTDio Exco (Valent Tan, Sharmayne Lim, Ferry Chandra, Janelle Ho, Joshua Ng)

**Logistical Details**
Refer to image attached (request to claim funds from DiscoverSUTD for introductory session due to scarce seed fund)
![image](https://user-images.githubusercontent.com/54134072/90360697-fcd4be00-e08e-11ea-9990-f4c9fa48f264.png)

Club email address: sutdio@club.sutd.edu.sg
Link to sign up form to be provided at a later date once event has been approved.

**Comment by jamestiotio** [comment]
Hi @sl194, since you require some budget from us, we will relay the approval process to be under OSA instead of OSL. We would need to request for approval from Registrar for this. The concern is less on the budget and more on safety due to the current COVID-19 situation.

I know that you have specified some of these details above, but to ease the process of email forwarding, could you email us [here](mailto:discover@sutd.edu.sg) with the following details:

1. What is the expected number of participants?
2. What is the kind of workshop/event that you are planning to conduct? Will it be conducted virtually or not? Give a slight description of what the participants are going to do for the workshop.
3. Do you need budget from OSA, and if yes, what is it for?
4. If the budget is to be used to purchase materials for the workshop, what is your proposed plan for collection? Give specific details such as the venue of collection, timing, and proposed human traffic management plan. Specify how you are going to control the human flow and prevent clustering/gathering. How are you going to ensure no cross-contamination? Also, reminder to conduct contact tracing per groups of 5.

We require specific details since Registrar would need to approve this proposal before we can allocate any budget for your team. Hope you understand.

**Comment by sl194** [comment]
Hi DiscoverSUTD team,

May we shift the event to one week later, on 24 September 2020, Thursday, 8-9pm? This is because we have yet to receive approval and we need time to prepare the materials so the timeline is rather tight. Sorry for the inconvenience and hope to receive your positive reply! Thank you!

**Comment by shohamc1** [comment]
Your new event time clashes with these other sessions on the 24th:
Tchoukball: 8.00 pm - 9.30 pm
SOAR: 7.30 pm - 9.45 pm
SUTD Climbers: 7.00pm - 9.30pm
SUTD Rotaract: 8.00 pm - 9.00 pm

Do you still want to proceed with the new date and time?

**Comment by sl194** [comment]
Hi DiscoverSUTD team, please review. Thank you!

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** In appeal*
**Remarks:**
- Late details submission

**Comment by sl194** [comment]
hi discoversutd team,
May I check regarding the progress of the approval of our freshmore intro session? Thank you!

**Comment by jiawei2912** [comment]
Update - 14 September 2020
Status: Approved
Remarks:
Budget of $81,30 is approved. Submit your claim receipts to OSA via the CONCUR system.

**Comment by jiawei2912** [comment]
Update - 15 September 2020
Status: Approved
List of additionally approved personnel:

- Valent Tan
- Sharmayne Lim
- Joshua Ng
- Ferry Chandra
- Janelle Janice Ho

Remarks:
-
